import {ProductInterface} from "@/components/product/Product.Interface";

export const productsList: ProductInterface[] = [
    {
        id : '2',
        name : 'Burger XXL',
        price: 14.99,
        description: 'Lorem Ipsum',
        image: '',
        foodType: 'Burger',
    },
    {
        id : '3',
        name : 'Burger BBQ',
        price: 13.99,
        description: 'Lorem Ipsum',
        image: '',
        foodType: 'Burger',
    },
    {
        id : '4',
        name : 'Burger Chicken',
        price: 11.99,
        description: 'Lorem Ipsum',
        image: '',
        foodType: 'Burger',
    },
    {
        id : '5',
        name : 'Burger Vegan',
        price: 10.99,
        description: 'Lorem Ipsum',
        image: '',
        foodType: 'Burger',
    },
    {
        id : '7',
        name : 'Fries Classic',
        price: 6.99,
        description: 'Lorem Ipsum',
        image: '',
        foodType: 'Fries',
    },
    {
        id : '8',
        name : 'Fries Twist',
        price: 7.99,
        description: 'Lorem Ipsum',
        image: '',
        foodType: 'Fries',
    },
    {
        id : '9',
        name : 'Fries Grandma',
        price: 7.99,
        description: 'Lorem Ipsum',
        image: '',
        foodType: 'Fries',
    },
    {
        id : '10',
        name : 'Fries XXL',
        price: 9.99,
        description: 'Lorem Ipsum',
        image: '',
        foodType: 'Fries',
    },
    {
        id : '12',
        name : 'Classic Coke',
        price: 3.99,
        description: 'Lorem Ipsum',
        image: '',
        foodType: 'Beverage',
    },
    {
        id : '13',
        name : 'Beer',
        price: 4.99,
        description: 'Lorem Ipsum',
        image: '',
        foodType: 'Beverage',
    },
    {
        id : '14',
        name : 'Water',
        price: 1.99,
        description: 'Lorem Ipsum',
        image: '',
        foodType: 'Beverage',
    }
];