import {useState} from "react";
import Head from 'next/head'
import styles from '@/styles/Home.module.scss'
import categories from '@/components/category/variables'
import Category from "@/components/category/Category";
import {ProductInterface} from "@/components/product/Interface";
import {productsList} from '@/components/product/variables'
import Header from "@/components/header/Header";
import CartProvider from "@/store/CartProvider";
import Product from "@/components/product/Product"

export default function Home() {
  const [category, setCategory] = useState('');

  return (
    <>
      <Head>
        <title>React Order Food</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
          <CartProvider>
            <Header />
            <div className={styles.main_return}>
              {(category !== '') && <button  onClick={ () => setCategory('')}>Return to Main Menu</button>}
            </div>
            <div className={styles.main_container}>
              {(category === '') && categories.map(category => (
                <Category key={category.id} title={category.title} image={category.image} handlerClick={setCategory} />
              ))}
              {(category !== '' ) &&
                <div className={styles.main_products}>
                    {(productsList.filter(product => product.foodType == category))
                      .map((product => (
                        <Product key={product.id} id={product.id} price={product.price} image={product.image} description={product.description} name={product.name} foodType={product.foodType} />
                      )))
                    }
                </div>
              }
            </div>
          </CartProvider>
      </main>
    </>
  )
}
