import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import categories from '@/components/category/variables'
import Category from "@/components/category/Category";
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [category, setCategory] = useState('noList');
  const [listToShow, setListToShow] = useState <ProductInterface[]> (
      {
        list: []
      }
  );

  useEffect( () => {
    productsList.forEach((listElement ) => {
      if(listElement.title === category) {
        setListToShow(listElement);
      }
    });

  }, [category]);
  return (
    <>
      <Head>
        <title>React Order Food</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className="App">
          <CartProvider>
            <Header />
            <div className="return-to-main-menu">
              {category !== 'noList' && <a  onClick={ () =>setCategory('noList')}>Return to Main Menu</a>}
            </div>
            <div className="App-body">
              {category === 'noList' && categories.map(category => (
                  <Category key={category.id} title={category.title} image={category.image} handlerClick={setCategory} />
              ))}
              {category !== 'noList' && <ProductsList id={listToShow?.id} image={listToShow.image} list={listToShow.list} title={listToShow.title}/>}
            </div>
          </CartProvider>
      </div>
      </main>
    </>
  )
}
